// This file is generated by Slice Machine. Update with care!

import EscolaProfile from './EscolaProfile';
import EscolaProfileImgs from './EscolaProfileImgs';
import EscolaRankDetail from './EscolaRankDetail';
import EscolaReclamacoes from './EscolaReclamacoes';

export {
	EscolaProfile,
	EscolaProfileImgs,
	EscolaRankDetail,
	EscolaReclamacoes,
};

export const components = {
	slice_teste_agora_vai: EscolaProfile,
	escola_profile_imgs: EscolaProfileImgs,
	teste: EscolaRankDetail,
	escola_reclamacoes: EscolaReclamacoes,
};
